site_name: Magentic Marketplace
site_description: Multi-agent marketplace platform documentation
site_url: https://microsoft.github.io/multi-agent-marketplace/

repo_url: https://github.com/microsoft/multi-agent-marketplace
repo_name: microsoft/multi-agent-marketplace

theme:
  name: material
  logo: magentic-m-white.svg
  favicon: magentic-m.svg
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Guide:
    - Overview: guide/00_tutorial.md
    - 1. Agents (BaseAgent, CustomerAgent, BusinessAgent): guide/01_agents__baseagent__customeragent__businessagent__.md
    - 2. Protocol & Actions: guide/02_protocol___actions_.md
    - 3. Marketplace Server: guide/03_marketplace_server_.md
    - 4. LLM Abstraction (generate function): guide/04_llm_abstraction___generate__function__.md
    - 5. Command-Line Interface (CLI) & Experiment Runners: guide/05_command_line_interface__cli____experiment_runners_.md
    - 6. Launchers (MarketplaceLauncher & AgentLauncher): guide/06_launchers__marketplacelauncher___agentlauncher__.md
    - 7. Database Controller: guide/07_database_controller_.md
  - Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
