[project]
name = "magentic-marketplace-mcp"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "magentic-marketplace",
    "mcp>=1.12.2"
]

[tool.uv.sources]
magentic-marketplace = {workspace = true}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/magentic_marketplace_mcp"]

[tool.ruff]
line-length = 88
target-version = "py313"
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    ".pytest_cache",
    "build",
    "dist",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
    "D", # docstrings
]
ignore = ["E501"]  # line too long

[tool.ruff.lint.isort]
known-first-party = ["agentic_economics"]

[tool.poe.tasks]
# Formatting tasks
format = "ruff format --check --diff"
format-fix = "ruff format"

# Linting tasks
lint = "ruff check"
lint-fix = "ruff check --fix --unsafe-fixes"

# Type checking tasks
type = "pyright src"
type-fix = """
pyright src --outputjson > /tmp/pyright_output.json 2>/dev/null || true
echo 'Type checking completed.'
"""

# Spell checking
spell = "codespell -I ../../.codespellignore src/**/*.py src/**/*.md"


# GitHub PR comments (shows comments for the active PR)
pr-comments = { shell = "PR_NUM=$(gh pr view --json number -q .number 2>/dev/null) && gh api repos/microsoft/agentic-economics/pulls/$PR_NUM/comments --jq '.[] | \"File: \" + (.path // \"N/A\") + \"\\nLine: \" + (.line // \"N/A\" | tostring) + \"\\nUser: \" + .user.login + \"\\nComment: \" + .body + \"\\n---\"' || echo 'No PR found for current branch. Make sure you are on a branch with an open PR.'" }

# Combined quality checks
check-all = ["format", "lint", "type", "spell"]
fix-all = ["format-fix", "lint-fix"]

[dependency-groups]
dev = [
    "codespell>=2.4.1",
    "poethepoet>=0.36.0",
    "pyright>=1.1.403",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.13.0",
]

[project.scripts]
magentic-marketplace-mcp = "magentic_marketplace_mcp.cli:main"