name: Ruff Linting

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Sync dependencies
      run: uv sync

    - name: Run ruff format check
      run: uv run ruff format --check --diff packages/magentic-marketplace/

    - name: Run ruff linting
      run: uv run ruff check packages/magentic-marketplace/
