name: Magentic-Marketplace Tests

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Sync dependencies
      run: uv sync

    - name: Run package-specific tests
      run: uv run pytest -m "not skip_ci and not rnr and not postgres" packages/magentic-marketplace/tests/

